### ISSUE TITLE
Better org id resolution handling

### ISSUE THREAD

**Issue by kylemanna** [infosechoudini/influxdb-rs#2]
Hi,

Thanks for this library, excited to use the 2.0 API vs the legacy interface for projects going forward!

Just ran into an issue where I created an auth token that was given only read/write access to a single bucket.  During `Client::new()` the library attempts to resolve `org` to `org_id` but fails for two reasons:

1. The permissions model of InfluxDB fails because the auth token needs the `read:/orgs` permission (aka `--read-orgs` flag during creation with CLI, this seems impossible via web UI) to query `api/v1/orgs`.
2. The client library doesn't expect an empty `org` response from the server as a result and `get_ord_id()` panics accessing `orgs[0]` as it's empty.

The code in question is [here](https://github.com/infosechoudini/influxdb-rs/blob/main/src/client.rs#L79):
```
                let org_id = contents.orgs[0].id.clone();
```

Not sure what the best solution here is.  Something like specifying the `orgId` to `Client::new_with_orig_id()` would skip the lookup and the need for that permission, but this doesn't feel very idiomatic.

At minimum it seems that the library should return an `Err()` if `contents.org.len() < 1`.

**Comment by infosechoudini** [comment]
i have some time today, i'll look at it!

**Comment by kylemanna** [comment]
Thanks!
