### ISSUE TITLE
api token fails 

### ISSUE THREAD

**Issue by rabarar** [infosechoudini/influxdb-rs#3]
generating a token that solely accesses a single bucket with read/write perms fails, but using a token with full access works.

Not only does it fail, but it fails within the call and doesn't return a `Result` from the call.

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/robert/.cargo/registry/src/github.com-1ecc6299db9ec823/influxdb_rs-0.2.0/src/client.rs:79:30
```

**Comment by rabarar** [comment]
here's the return from the call on client.rs:79:30 to get the orgs:
`contents: Orgs { links: Links { next: None, prev: None, link_self: Some("/api/v2/orgs") }, orgs: [] }`

clearly an empty orgs is unexpected ...

**Comment by infosechoudini** [comment]
I have some free time today, i'll look at it!

**Comment by rabarar** [comment]
Sounds great! No rushOn Apr 20, 2023, at 10:58 AM, Harry Thomas ***@***.***> wrote:﻿
I have some free time today, i'll look at it!

**Comment by infosechoudini** [comment]
fixed!!! you can also generate a token via this crate as well

**Comment by rabarar** [comment]
nice! I’m guessing it was an influx API issue?

**Comment by rabarar** [comment]
thanks for the quick fix!

**Comment by infosechoudini** [comment]
no worries!!! you caught me on a good day!!!!!
